name: bloc_counter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
